version: '3.3'
services:
  api:
    container_name: 'api'
    build: './api'
    ports:
      - '8080:8080'
    volumes:
      - './api:/go/src/app'
  angular-client:
    container_name: 'angular-client'
    build: 'angular-client'
    ports:
      - '4200:4200'
    # volumes:
    #   - './angular-client:/usr/src/app'